### ISSUE TITLE
Problem with 'Helvetica Neue'  font on  android

### ISSUE THREAD

**Issue by stalb** [joshjhargreaves/react-native-event-calendar#30]
On android, I get this error message:

> fontFamily "Helvetica Neue" is not a system font and has not been loaded through Font.loadAsync.
> 
> - If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
> 
> - If this is a custom font, be sure to load it with Font.loadAsync.
> - node_modules\react-native\Libraries\YellowBox\YellowBox.js:59:8 in error
> - node_modules\expo-font\build\Font.js:24:16 in processFontFamily
> - ... 24 more stack frames from framework internals

In fact Apple has replaced 'Helvetica' by 'Helvetica Neue' but Google on android prefers 'Robot'.
See also stack overflow question here: https://stackoverflow.com/questions/52069960/console-error-fontfamily-helvetica-neue-is-not-a-system-font-and-has-not-bee

**Comment by stalb** [comment]
fixed by PR #31

**Comment by gr0x0** [comment]
I am still getting this error. I have version 1.0.8 of react-native-event-calendar installed in my project. 
In this version, when checking the style.js on node_modules/react-native-events-calendar I don't see the corrected line

> fontFamily: Platform.OS === 'ios' ? 'Helvetica Neue' : 'Roboto',

Instead, I still see 

> fontFamily: 'Helvetica Neue',

I am doing something wrong?

**Comment by javierarancibia** [comment]
In case you are using the useFonts hook, I fixed this problem updating my nodes with npm update. This fixed it!
